package Midterms.midlab2.GUI;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class DecryptionHuffmanCode extends javax.swing.JInternalFrame {

    /**
     * Creates new form DecryptionHuffmanCode
     */
    public DecryptionHuffmanCode() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        huffmanCodeLabel = new javax.swing.JLabel();
        huffmanCodeTextScroll = new javax.swing.JScrollPane();
        huffmanCodeTextArea = new javax.swing.JTextArea();
        decodedTextLabel = new javax.swing.JLabel();
        decodedTextScrollText = new javax.swing.JScrollPane();
        decodedTextArea = new javax.swing.JTextArea();
        decodeToTextButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        tableOfValuesScrollPane = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        huffmanCodeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        huffmanCodeLabel.setText("Enter Huffman Code:");

        huffmanCodeTextScroll.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        huffmanCodeTextArea.setColumns(20);
        huffmanCodeTextArea.setRows(5);
        huffmanCodeTextScroll.setViewportView(huffmanCodeTextArea);

        decodedTextLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        decodedTextLabel.setText("Decoded Text:");

        decodedTextArea.setColumns(20);
        decodedTextArea.setRows(5);
        decodedTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        decodedTextScrollText.setViewportView(decodedTextArea);

        decodeToTextButton.setBackground(new java.awt.Color(255, 219, 87));
        decodeToTextButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        decodeToTextButton.setText("Decode To Text");
        decodeToTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeToTextButtonActionPerformed(evt);
            }
        });

        tableOfValuesScrollPane.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Title 1", "Title 2"
                }
        ));
        tableScrollPane.setViewportView(tableOfValuesScrollPane);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Table Of Values");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(575, 575, 575)
                                                .addComponent(decodeToTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(huffmanCodeLabel)
                                                        .addComponent(decodedTextLabel)
                                                        .addComponent(huffmanCodeTextScroll)
                                                        .addComponent(decodedTextScrollText)
                                                        .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(616, 616, 616)
                                                .addComponent(jLabel1)))
                                .addContainerGap(14993, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(huffmanCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(huffmanCodeTextScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(decodedTextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decodedTextScrollText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(decodeToTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void decodeToTextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton decodeToTextButton;
    private javax.swing.JTextArea decodedTextArea;
    private javax.swing.JLabel decodedTextLabel;
    private javax.swing.JScrollPane decodedTextScrollText;
    private javax.swing.JLabel huffmanCodeLabel;
    private javax.swing.JTextArea huffmanCodeTextArea;
    private javax.swing.JScrollPane huffmanCodeTextScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tableOfValuesScrollPane;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration
}
