/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Midterms.midlab2.GUI;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class EncryptionHuffmanCode extends javax.swing.JInternalFrame {

    /**
     * Creates new form EncryptionHuffmanCode
     */
    public EncryptionHuffmanCode() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textInput = new javax.swing.JLabel();
        huffmanCodeLabel = new javax.swing.JLabel();
        EncodeButton = new javax.swing.JButton();
        TableScrollPane = new javax.swing.JScrollPane();
        TtableOfValues = new javax.swing.JTable();
        textInputScrollPane = new javax.swing.JScrollPane();
        textInputTextArea = new javax.swing.JTextArea();
        huffmanCodePane = new javax.swing.JScrollPane();
        huffmanCodeTextArea = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textInput.setText("Enter a text: ");

        huffmanCodeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        huffmanCodeLabel.setText("Huffman Code:");

        EncodeButton.setBackground(new java.awt.Color(255, 219, 87));
        EncodeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EncodeButton.setText("Encode to Huffman");
        EncodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncodeButtonMouseEntered(evt);
            }
        });
        EncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncodeButtonActionPerformed(evt);
            }
        });

        TtableOfValues.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        TableScrollPane.setViewportView(TtableOfValues);

        textInputTextArea.setColumns(20);
        textInputTextArea.setRows(5);
        textInputScrollPane.setViewportView(textInputTextArea);

        huffmanCodeTextArea.setColumns(20);
        huffmanCodeTextArea.setRows(5);
        huffmanCodePane.setViewportView(huffmanCodeTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(huffmanCodePane, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textInputScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(387, 387, 387)
                                                                .addComponent(EncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(TableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textInput)
                                                        .addComponent(huffmanCodeLabel))
                                                .addGap(1, 1, 1)))
                                .addContainerGap(15161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(textInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(huffmanCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(huffmanCodePane, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void EncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void EncodeButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton EncodeButton;
    private javax.swing.JScrollPane TableScrollPane;
    private javax.swing.JTable TtableOfValues;
    private javax.swing.JLabel huffmanCodeLabel;
    private javax.swing.JScrollPane huffmanCodePane;
    private javax.swing.JTextArea huffmanCodeTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textInput;
    private javax.swing.JScrollPane textInputScrollPane;
    private javax.swing.JTextArea textInputTextArea;
    // End of variables declaration
}
