/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Midterms.midlab2.GUI;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class StorageSavingsPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form StorageSavingsPage
     */
    public StorageSavingsPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        huffmanCodingLabel = new javax.swing.JLabel();
        asciiCodingLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        huffmanCodingComputationTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        asciiCodingComputationTextArea = new javax.swing.JTextArea();
        computationLabel1 = new javax.swing.JLabel();
        computationLabel2 = new javax.swing.JLabel();
        storageSavingsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storageSavingsResultTextArea = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        huffmanCodingLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        huffmanCodingLabel.setText("HUFFMAN CODING");

        asciiCodingLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        asciiCodingLabel.setText("ASCII CODING");

        huffmanCodingComputationTextArea.setColumns(20);
        huffmanCodingComputationTextArea.setRows(5);
        huffmanCodingComputationTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        huffmanCodingComputationTextArea.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(huffmanCodingComputationTextArea);

        asciiCodingComputationTextArea.setColumns(20);
        asciiCodingComputationTextArea.setRows(5);
        asciiCodingComputationTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane3.setViewportView(asciiCodingComputationTextArea);

        computationLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        computationLabel1.setText("Computation");

        computationLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        computationLabel2.setText("Computation");

        storageSavingsLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        storageSavingsLabel.setForeground(new java.awt.Color(0, 80, 157));
        storageSavingsLabel.setText("Storage Savings (%):");

        storageSavingsResultTextArea.setColumns(5);
        storageSavingsResultTextArea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        storageSavingsResultTextArea.setRows(1);
        storageSavingsResultTextArea.setTabSize(3);
        storageSavingsResultTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jScrollPane1.setViewportView(storageSavingsResultTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(huffmanCodingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(156, 156, 156)
                                                                .addComponent(asciiCodingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(54, 54, 54)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(549, 549, 549)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(564, 564, 564)
                                                .addComponent(storageSavingsLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(311, 311, 311)
                                                .addComponent(computationLabel1)
                                                .addGap(539, 539, 539)
                                                .addComponent(computationLabel2)))
                                .addContainerGap(13758, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(huffmanCodingLabel)
                                        .addComponent(asciiCodingLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(computationLabel1)
                                        .addComponent(computationLabel2))
                                .addGap(56, 56, 56)
                                .addComponent(storageSavingsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(307, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JTextArea asciiCodingComputationTextArea;
    private javax.swing.JLabel asciiCodingLabel;
    private javax.swing.JLabel computationLabel1;
    private javax.swing.JLabel computationLabel2;
    private javax.swing.JTextArea huffmanCodingComputationTextArea;
    private javax.swing.JLabel huffmanCodingLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel storageSavingsLabel;
    private javax.swing.JTextArea storageSavingsResultTextArea;
    // End of variables declaration
}
